name: ed25519spacemesh
description: Native ed25519 implementation for Spacemesh.io
version: 0.0.3
homepage: https://github.com/andreivdev/ed25519spacemesh

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  bip32: ^2.0.0
  convert: ^3.0.0
  cryptography: ^2.0.1
  collection: ^1.15.0
